# Create docker image for scStudio - Differential Expression Analysis
name: Build Docker Image (dea)

on:
  push:
    branches:
      - main
    paths:
      - 'dea/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_MB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_MB_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./dea    
        file: ./dea/Dockerfile  
        push: true
        tags: ${{ secrets.DOCKERHUB_MB_USERNAME }}/scstudio-dea:1.2
