# Create docker image for scStudio - Functional Enrichment Analysis
name: Build Docker Image (fea)

on:
  push:
    branches:
      - main
    paths:
      - 'fea/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_MB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_MB_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./fea    
        file: ./fea/Dockerfile  
        push: true
<<<<<<< HEAD
        tags: ${{ secrets.DOCKERHUB_MB_USERNAME }}/scstudio-fea:1.2
=======
        tags: ${{ secrets.DOCKERHUB_MB_USERNAME }}/scstudio-fea:1.3
>>>>>>> 8d5dffa784b6ba4ae81892ad47d658eb039b04de
