# Create docker image for scStudio - Report
name: Build Docker Image (report)

on:
  push:
    branches:
      - main
    paths:
      - 'report/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_MB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_MB_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./report   
        file: ./report/Dockerfile  
        push: true
        tags: ${{ secrets.DOCKERHUB_MB_USERNAME }}/scstudio-report:1.1
